import React, { useState, useEffect } from 'react'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Image from 'next/image'
import dummy from '../assets/dummy.png'
import Head from 'next/head'
import { useRouter } from 'next/router'

/**@file App.js this is the first page to get rendered <br />
this is the first page to get rendered.<br />
it includes head tag. which changes the title of the page and favicon.<br />
a header component, the homeScreen content and the footer component<br />
*/
function index() {
  // //* a variable to change the footer text color
  // const [show, handleShow] = useState(false)
  // //* function to change the variable to change footer text color
  // const transitionNavBar = () => {
  //   if (window.scrollY > 0) {
  //     handleShow(true)
  //   } else {
  //     handleShow(false)
  //   }
  // }

  // useEffect(() => {
  //   window.addEventListener('scroll', transitionNavBar)
  //   return () => window.removeEventListener('scroll', transitionNavBar)
  // }, [])

  //* a variable to use useRouter hook
  const router = useRouter()

  const moveToContact = () => {
    router.push('/contactus')
  }
  return (
    <div className="">
      <Head>
        <title>ValueStory</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico?v=2" />
      </Head>
      <div
        className="fixed top-0 z-50 w-full bg-[#3a3a3a50]"
        data-test="header"
      >
        <Header />
      </div>

      <div data-test="background-video">
        <video
          autoPlay={true}
          loop={true}
          playsInline={true}
          muted
          style={{ width: '100%' }}
        >
          <source type="video/mp4" src={'/demo.mp4'} />
        </video>
      </div>

      <div
        className="mx-auto flex max-w-7xl flex-col items-center justify-center lg:flex-row"
        data-test="description"
      >
        <div className="z-30 flex w-full max-w-xl flex-shrink-0 flex-grow flex-col items-center text-center lg:w-1/2 lg:text-left">
          <h1 className="mb-4 text-center text-3xl font-black leading-tight text-gray-900 sm:text-6xl xl:mb-8">
            Build the Next Great Thing
          </h1>
          <p className="mb-8 pr-0 text-center text-base text-gray-600 sm:text-lg  xl:text-xl">
            Are you ready to start your adventure and start building the next
            greatest SAAS app on the market?
          </p>
          <button
            data-test="signup-button"
            className="button fold-bold w-auto px-8 py-4 shadow-xl"
            onClick={moveToContact}
          >
            Signup Today!
          </button>
        </div>

        <div className="relative h-56 w-80 sm:h-[450px] sm:w-[700px] md:w-[750px] lg:w-[980px]">
          <Image src={dummy} layout="fill" objectFit="contain" priority />
        </div>
      </div>
      {/* <div className="h-20" /> */}
      {/* <div
        className={`fixed bottom-0 z-50 w-full bg-transparent ${
          show ? 'text-black' : 'text-white'
        }`}
      >
        <Footer />
      </div> */}
    </div>
  )
}

export default index
